server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: auth

  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop

  datasource:
    url: jdbc:postgresql://localhost:5434/auth_db
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
