server:
  port: 8080

services:
  auth:
    uri: ${AUTH_SERVICE_URI:http://localhost:8081}
  billing:
    uri: ${BILLING_SERVICE_URI:http://localhost:8082}

jwt:
  secret: ${JWT_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service-auth
          uri: ${services.auth.uri}
          predicates:
            - Path=/auth/**

        - id: billing-service
          uri: ${services.billing.uri}
          predicates:
            - Path=/billing/**
          filters:
            - StripPrefix=1



