/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.billMate.billing.infrastructure.rest.api;

import com.billMate.billing.infrastructure.rest.dto.ApiError;
import com.billMate.billing.infrastructure.rest.dto.ClientDTO;
import com.billMate.billing.infrastructure.rest.dto.NewClientDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-02T01:11:33.737203500+01:00[Europe/Madrid]")
@Validated
@Tag(name = "clients", description = "Endpoints para gestión de clientes")
public interface ClientsApi {

    /**
     * POST /clients : Crear nuevo cliente
     *
     * @param newClientDTO  (required)
     * @return Cliente creado (status code 201)
     *         or Petición mal formada (status code 400)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "createClient",
        summary = "Crear nuevo cliente",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Cliente creado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/clients",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ClientDTO> createClient(
        @Parameter(name = "NewClientDTO", description = "", required = true) @Valid @RequestBody NewClientDTO newClientDTO
    );


    /**
     * DELETE /clients/{clientId} : Eliminar cliente por ID
     *
     * @param clientId  (required)
     * @return Cliente eliminado exitosamente (status code 204)
     *         or Petición mal formada (status code 400)
     *         or Cliente no encontrado (status code 404)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "deleteClient",
        summary = "Eliminar cliente por ID",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Cliente eliminado exitosamente"),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/clients/{clientId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteClient(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Long clientId
    );


    /**
     * GET /clients/{clientId} : Obtener cliente por ID
     *
     * @param clientId  (required)
     * @return Cliente encontrado (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Cliente no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getClientById",
        summary = "Obtener cliente por ID",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clients/{clientId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<ClientDTO> getClientById(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Long clientId
    );


    /**
     * GET /clients : Obtener todos los clientes
     *
     * @return Lista de clientes (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getClients",
        summary = "Obtener todos los clientes",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de clientes", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ClientDTO.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clients",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<ClientDTO>> getClients(
        
    );


    /**
     * PUT /clients/{clientId} : Actualizar cliente existente
     *
     * @param clientId  (required)
     * @param newClientDTO  (required)
     * @return Cliente actualizado (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Cliente no encontrado (status code 404)
     *         or Acceso no autorizado (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "updateClient",
        summary = "Actualizar cliente existente",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente actualizado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso no autorizado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/clients/{clientId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ClientDTO> updateClient(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Long clientId,
        @Parameter(name = "NewClientDTO", description = "", required = true) @Valid @RequestBody NewClientDTO newClientDTO
    );

}
