/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.billMate.billing.infrastructure.rest.api;

import com.billMate.billing.infrastructure.rest.dto.ApiError;
import com.billMate.billing.infrastructure.rest.dto.ClientDTO;
import com.billMate.billing.infrastructure.rest.dto.ClientPageDTO;
import com.billMate.billing.infrastructure.rest.dto.NewClientDTO;
import org.springframework.lang.Nullable;
import com.billMate.billing.infrastructure.rest.dto.PatchClientDTO;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-26T00:19:34.971748300+01:00[Europe/Madrid]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "clients", description = "Endpoints para gestión de clientes")
public interface ClientsApi {

    String PATH_CREATE_CLIENT = "/clients";
    /**
     * POST /clients : Crear nuevo cliente
     *
     * @param newClientDTO  (required)
     * @param idempotencyKey UUID único para garantizar idempotencia. Si se envía la misma clave en una segunda llamada, se devuelve la respuesta original sin crear duplicados. TTL: 24h. (optional)
     * @return Cliente creado (status code 201)
     *         or Petición mal formada (status code 400)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "createClient",
        summary = "Crear nuevo cliente",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Cliente creado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDTO.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"id\":1,\"name\":\"Juan Pérez\",\"email\":\"juanperez@mail.com\",\"phone\":\"+34 600 123 456\",\"nif\":\"12345678Z\",\"address\":\"Calle Falsa 123, Madrid\",\"createdAt\":\"2025-05-15T14:30:00Z\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ClientsApi.PATH_CREATE_CLIENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ClientDTO> createClient(
        @Parameter(name = "NewClientDTO", description = "", required = true) @Valid @RequestBody NewClientDTO newClientDTO,
        @Parameter(name = "Idempotency-Key", description = "UUID único para garantizar idempotencia. Si se envía la misma clave en una segunda llamada, se devuelve la respuesta original sin crear duplicados. TTL: 24h.", in = ParameterIn.HEADER) @RequestHeader(value = "Idempotency-Key", required = false) @Nullable UUID idempotencyKey
    );


    String PATH_DELETE_CLIENT = "/clients/{clientId}";
    /**
     * DELETE /clients/{clientId} : Eliminar cliente por ID
     *
     * @param clientId  (required)
     * @return Cliente eliminado exitosamente (status code 204)
     *         or Petición mal formada (status code 400)
     *         or Cliente no encontrado (status code 404)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "deleteClient",
        summary = "Eliminar cliente por ID",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Cliente eliminado exitosamente"),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ClientsApi.PATH_DELETE_CLIENT,
        produces = { "application/json" }
    )
    ResponseEntity<Void> deleteClient(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Long clientId
    );


    String PATH_GET_CLIENT_BY_ID = "/clients/{clientId}";
    /**
     * GET /clients/{clientId} : Obtener cliente por ID
     *
     * @param clientId  (required)
     * @return Cliente encontrado (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Cliente no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getClientById",
        summary = "Obtener cliente por ID",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDTO.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"id\":1,\"name\":\"Juan Pérez\",\"email\":\"juanperez@mail.com\",\"phone\":\"+34 600 123 456\",\"nif\":\"12345678Z\",\"address\":\"Calle Falsa 123, Madrid\",\"createdAt\":\"2025-05-15T14:30:00Z\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ClientsApi.PATH_GET_CLIENT_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<ClientDTO> getClientById(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Long clientId
    );


    String PATH_GET_CLIENTS = "/clients";
    /**
     * GET /clients : Obtener todos los clientes
     *
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param sort Ordenación. Formato: campo,dirección (ej: name,asc). Campos válidos: name, email, nif, createdAt. (optional, default to createdAt,desc)
     * @param name Filtrar por nombre (búsqueda parcial, insensible a mayúsculas). (optional)
     * @param nif Filtrar por NIF exacto. (optional)
     * @return Página de clientes (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getClients",
        summary = "Obtener todos los clientes",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Página de clientes", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientPageDTO.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "[{\"id\":1,\"name\":\"Juan Pérez\",\"email\":\"juanperez@mail.com\",\"phone\":\"+34 600 123 456\",\"nif\":\"12345678Z\",\"address\":\"Calle Falsa 123, Madrid\",\"createdAt\":\"2025-05-15T14:30:00Z\"}]"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ClientsApi.PATH_GET_CLIENTS,
        produces = { "application/json" }
    )
    ResponseEntity<ClientPageDTO> getClients(
        @Min(value = 0) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(value = 1) @Max(value = 20) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size,
        @Parameter(name = "sort", description = "Ordenación. Formato: campo,dirección (ej: name,asc). Campos válidos: name, email, nif, createdAt.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false, defaultValue = "createdAt,desc") String sort,
        @Parameter(name = "name", description = "Filtrar por nombre (búsqueda parcial, insensible a mayúsculas).", in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = false) @Nullable String name,
        @Parameter(name = "nif", description = "Filtrar por NIF exacto.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "nif", required = false) @Nullable String nif
    );


    String PATH_PATCH_CLIENT = "/clients/{clientId}";
    /**
     * PATCH /clients/{clientId} : Actualizar parcialmente un cliente (JSON Merge Patch)
     * Actualiza solo los campos incluidos en el body. Los campos ausentes se mantienen sin cambios (RFC 7396).
     *
     * @param clientId  (required)
     * @param patchClientDTO  (required)
     * @return Cliente actualizado parcialmente (status code 200)
     *         or Datos de actualización inválidos (status code 400)
     *         or Cliente no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "patchClient",
        summary = "Actualizar parcialmente un cliente (JSON Merge Patch)",
        description = "Actualiza solo los campos incluidos en el body. Los campos ausentes se mantienen sin cambios (RFC 7396).",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente actualizado parcialmente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Datos de actualización inválidos", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = ClientsApi.PATH_PATCH_CLIENT,
        produces = { "application/json" },
        consumes = { "application/merge-patch+json" }
    )
    ResponseEntity<ClientDTO> patchClient(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Long clientId,
        @Parameter(name = "PatchClientDTO", description = "", required = true) @Valid @RequestBody PatchClientDTO patchClientDTO
    );


    String PATH_UPDATE_CLIENT = "/clients/{clientId}";
    /**
     * PUT /clients/{clientId} : Actualizar cliente existente
     *
     * @param clientId  (required)
     * @param newClientDTO  (required)
     * @return Cliente actualizado (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Cliente no encontrado (status code 404)
     *         or Acceso no autorizado (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "updateClient",
        summary = "Actualizar cliente existente",
        tags = { "clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente actualizado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDTO.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"clientId\":1,\"name\":\"Juan Pérez\",\"email\":\"juanperez@mail.com\",\"phone\":\"+34 600 123 456\",\"nif\":\"12345678Z\",\"address\":\"Calle Falsa 123, Madrid\",\"createdAt\":\"2025-05-15T14:30:00Z\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso no autorizado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ClientsApi.PATH_UPDATE_CLIENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ClientDTO> updateClient(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Long clientId,
        @Parameter(name = "NewClientDTO", description = "", required = true) @Valid @RequestBody NewClientDTO newClientDTO
    );

}
