/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.billMate.billing.infrastructure.rest.api;

import com.billMate.billing.infrastructure.rest.dto.ApiError;
import com.billMate.billing.infrastructure.rest.dto.InvoiceDTO;
import com.billMate.billing.infrastructure.rest.dto.NewInvoiceDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-02T01:11:33.737203500+01:00[Europe/Madrid]")
@Validated
@Tag(name = "invoices", description = "Endpoints para gestión de facturas")
public interface InvoicesApi {

    /**
     * POST /invoices : Crear una nueva factura
     *
     * @param newInvoiceDTO  (required)
     * @return Factura creada correctamente (status code 201)
     *         or Petición mal formada (status code 400)
     *         or Error interno (status code 500)
     */
    @Operation(
        operationId = "createInvoice",
        summary = "Crear una nueva factura",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Factura creada correctamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/invoices",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<InvoiceDTO> createInvoice(
        @Parameter(name = "NewInvoiceDTO", description = "", required = true) @Valid @RequestBody NewInvoiceDTO newInvoiceDTO
    );


    /**
     * DELETE /invoices/{invoiceId} : Eliminar factura por ID
     *
     * @param invoiceId  (required)
     * @return Factura eliminada correctamente (status code 204)
     *         or Petición mal formada (status code 400)
     *         or Factura no encontrada (status code 404)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "deleteInvoice",
        summary = "Eliminar factura por ID",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Factura eliminada correctamente"),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/invoices/{invoiceId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteInvoice(
        @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    /**
     * GET /invoices/{invoiceId}/pdf : Descargar el PDF de una factura
     * Devuelve un archivo PDF solo si la factura ya ha sido emitida.
     *
     * @param invoiceId  (required)
     * @return PDF generado correctamente (status code 200)
     *         or Factura no válida para descarga (status code 400)
     *         or Factura no encontrada (status code 404)
     */
    @Operation(
        operationId = "downloadInvoicePdf",
        summary = "Descargar el PDF de una factura",
        description = "Devuelve un archivo PDF solo si la factura ya ha sido emitida.",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "PDF generado correctamente", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = org.springframework.core.io.Resource.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            }),
            @ApiResponse(responseCode = "400", description = "Factura no válida para descarga", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices/{invoiceId}/pdf",
        produces = { "application/pdf", "application/json" }
    )
    
    ResponseEntity<org.springframework.core.io.Resource> downloadInvoicePdf(
        @Min(1L) @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    /**
     * PUT /invoices/{invoiceId}/emit : Emitir una factura en estado DRAFT
     * Cambia el estado de la factura a SENT y genera un PDF.
     *
     * @param invoiceId  (required)
     * @return PDF generado correctamente (status code 200)
     *         or No se puede emitir una factura que no esté en estado DRAFT (status code 400)
     *         or Factura no encontrada (status code 404)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "emitInvoice",
        summary = "Emitir una factura en estado DRAFT",
        description = "Cambia el estado de la factura a SENT y genera un PDF.",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "PDF generado correctamente", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = org.springframework.core.io.Resource.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            }),
            @ApiResponse(responseCode = "400", description = "No se puede emitir una factura que no esté en estado DRAFT", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/invoices/{invoiceId}/emit",
        produces = { "application/pdf", "application/json" }
    )
    
    ResponseEntity<org.springframework.core.io.Resource> emitInvoice(
        @Min(1L) @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    /**
     * GET /invoices/{invoiceId} : Obtener factura por ID
     *
     * @param invoiceId  (required)
     * @return Factura encontrada (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Factura no encontrada (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getInvoiceById",
        summary = "Obtener factura por ID",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Factura encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices/{invoiceId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<InvoiceDTO> getInvoiceById(
        @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    /**
     * GET /invoices : Obtener todas las facturas
     *
     * @return Lista de facturas (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getInvoices",
        summary = "Obtener todas las facturas",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de facturas", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = InvoiceDTO.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<InvoiceDTO>> getInvoices(
        
    );


    /**
     * GET /invoices/client/{clientId} : Obtener todas las facturas de un cliente
     *
     * @param clientId  (required)
     * @return Lista de facturas del cliente (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Cliente no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getInvoicesByClientId",
        summary = "Obtener todas las facturas de un cliente",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de facturas del cliente", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = InvoiceDTO.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices/client/{clientId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<InvoiceDTO>> getInvoicesByClientId(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Long clientId
    );


    /**
     * PUT /invoices/{invoiceId}/pay : Marcar factura como pagada
     * Cambia el estado de la factura a PAID.
     *
     * @param invoiceId  (required)
     * @return Factura actualizada a pagada (status code 200)
     *         or Factura no se puede pagar (status code 400)
     *         or Factura no encontrada (status code 404)
     *         or Acceso denegado (status code 403)
     *         or Error interno (status code 500)
     */
    @Operation(
        operationId = "payInvoice",
        summary = "Marcar factura como pagada",
        description = "Cambia el estado de la factura a PAID.",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Factura actualizada a pagada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Factura no se puede pagar", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso denegado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/invoices/{invoiceId}/pay",
        produces = { "application/json" }
    )
    
    ResponseEntity<InvoiceDTO> payInvoice(
        @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    /**
     * PUT /invoices/{invoiceId} : Actualizar factura existente
     *
     * @param invoiceId  (required)
     * @param newInvoiceDTO  (required)
     * @return Factura actualizada correctamente (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Factura no encontrada (status code 404)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "updateInvoice",
        summary = "Actualizar factura existente",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Factura actualizada correctamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/invoices/{invoiceId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<InvoiceDTO> updateInvoice(
        @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId,
        @Parameter(name = "NewInvoiceDTO", description = "", required = true) @Valid @RequestBody NewInvoiceDTO newInvoiceDTO
    );

}
