/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.billMate.billing.infrastructure.rest.api;

import com.billMate.billing.infrastructure.rest.dto.ApiError;
import org.springframework.format.annotation.DateTimeFormat;
import com.billMate.billing.infrastructure.rest.dto.InvoiceDTO;
import com.billMate.billing.infrastructure.rest.dto.InvoicePageDTO;
import java.time.LocalDate;
import com.billMate.billing.infrastructure.rest.dto.NewInvoiceDTO;
import org.springframework.lang.Nullable;
import com.billMate.billing.infrastructure.rest.dto.PatchInvoiceDTO;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-26T00:11:19.317367700+01:00[Europe/Madrid]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "invoices", description = "Endpoints para gestión de facturas")
public interface InvoicesApi {

    String PATH_CREATE_INVOICE = "/invoices";
    /**
     * POST /invoices : Crear una nueva factura
     *
     * @param newInvoiceDTO  (required)
     * @param idempotencyKey UUID único para garantizar idempotencia. Si se envía la misma clave en una segunda llamada, se devuelve la respuesta original sin crear duplicados. TTL: 24h. (optional)
     * @return Factura creada correctamente (status code 201)
     *         or Petición mal formada (status code 400)
     *         or Error interno (status code 500)
     */
    @Operation(
        operationId = "createInvoice",
        summary = "Crear una nueva factura",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Factura creada correctamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = InvoicesApi.PATH_CREATE_INVOICE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<InvoiceDTO> createInvoice(
        @Parameter(name = "NewInvoiceDTO", description = "", required = true) @Valid @RequestBody NewInvoiceDTO newInvoiceDTO,
        @Parameter(name = "Idempotency-Key", description = "UUID único para garantizar idempotencia. Si se envía la misma clave en una segunda llamada, se devuelve la respuesta original sin crear duplicados. TTL: 24h.", in = ParameterIn.HEADER) @RequestHeader(value = "Idempotency-Key", required = false) @Nullable UUID idempotencyKey
    );


    String PATH_DELETE_INVOICE = "/invoices/{invoiceId}";
    /**
     * DELETE /invoices/{invoiceId} : Eliminar factura por ID
     *
     * @param invoiceId  (required)
     * @return Factura eliminada correctamente (status code 204)
     *         or Petición mal formada (status code 400)
     *         or Factura no encontrada (status code 404)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "deleteInvoice",
        summary = "Eliminar factura por ID",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Factura eliminada correctamente"),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = InvoicesApi.PATH_DELETE_INVOICE,
        produces = { "application/json" }
    )
    ResponseEntity<Void> deleteInvoice(
        @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    String PATH_DOWNLOAD_INVOICE_PDF = "/invoices/{invoiceId}/pdf";
    /**
     * GET /invoices/{invoiceId}/pdf : Descargar el PDF de una factura
     * Devuelve un archivo PDF solo si la factura ya ha sido emitida.
     *
     * @param invoiceId  (required)
     * @return PDF generado correctamente (status code 200)
     *         or Factura no válida para descarga (status code 400)
     *         or Factura no encontrada (status code 404)
     */
    @Operation(
        operationId = "downloadInvoicePdf",
        summary = "Descargar el PDF de una factura",
        description = "Devuelve un archivo PDF solo si la factura ya ha sido emitida.",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "PDF generado correctamente", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = org.springframework.core.io.Resource.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            }),
            @ApiResponse(responseCode = "400", description = "Factura no válida para descarga", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = InvoicesApi.PATH_DOWNLOAD_INVOICE_PDF,
        produces = { "application/pdf", "application/json" }
    )
    ResponseEntity<org.springframework.core.io.Resource> downloadInvoicePdf(
        @Min(value = 1L) @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    String PATH_EMIT_INVOICE = "/invoices/{invoiceId}/emit";
    /**
     * PUT /invoices/{invoiceId}/emit : Emitir una factura en estado DRAFT
     * Cambia el estado de la factura a SENT y genera un PDF.
     *
     * @param invoiceId  (required)
     * @return PDF generado correctamente (status code 200)
     *         or No se puede emitir una factura que no esté en estado DRAFT (status code 400)
     *         or Factura no encontrada (status code 404)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "emitInvoice",
        summary = "Emitir una factura en estado DRAFT",
        description = "Cambia el estado de la factura a SENT y genera un PDF.",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "PDF generado correctamente", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = org.springframework.core.io.Resource.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            }),
            @ApiResponse(responseCode = "400", description = "No se puede emitir una factura que no esté en estado DRAFT", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = ApiError.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = InvoicesApi.PATH_EMIT_INVOICE,
        produces = { "application/pdf", "application/json" }
    )
    ResponseEntity<org.springframework.core.io.Resource> emitInvoice(
        @Min(value = 1L) @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    String PATH_GET_INVOICE_BY_ID = "/invoices/{invoiceId}";
    /**
     * GET /invoices/{invoiceId} : Obtener factura por ID
     *
     * @param invoiceId  (required)
     * @return Factura encontrada (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Factura no encontrada (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getInvoiceById",
        summary = "Obtener factura por ID",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Factura encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = InvoicesApi.PATH_GET_INVOICE_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<InvoiceDTO> getInvoiceById(
        @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    String PATH_GET_INVOICES = "/invoices";
    /**
     * GET /invoices : Obtener todas las facturas
     *
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param sort Ordenación. Formato: campo,dirección (ej: date,asc). Campos válidos: date, total, status, createdAt. (optional, default to createdAt,desc)
     * @param status Filtrar por estado de la factura. (optional)
     * @param dateFrom Filtrar facturas con fecha mayor o igual a esta (formato: YYYY-MM-DD). (optional)
     * @param dateTo Filtrar facturas con fecha menor o igual a esta (formato: YYYY-MM-DD). (optional)
     * @return Página de facturas (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getInvoices",
        summary = "Obtener todas las facturas",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Página de facturas", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoicePageDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = InvoicesApi.PATH_GET_INVOICES,
        produces = { "application/json" }
    )
    ResponseEntity<InvoicePageDTO> getInvoices(
        @Min(value = 0) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(value = 1) @Max(value = 20) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size,
        @Parameter(name = "sort", description = "Ordenación. Formato: campo,dirección (ej: date,asc). Campos válidos: date, total, status, createdAt.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false, defaultValue = "createdAt,desc") String sort,
        @Parameter(name = "status", description = "Filtrar por estado de la factura.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) @Nullable String status,
        @Parameter(name = "dateFrom", description = "Filtrar facturas con fecha mayor o igual a esta (formato: YYYY-MM-DD).", in = ParameterIn.QUERY) @Valid @RequestParam(value = "dateFrom", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate dateFrom,
        @Parameter(name = "dateTo", description = "Filtrar facturas con fecha menor o igual a esta (formato: YYYY-MM-DD).", in = ParameterIn.QUERY) @Valid @RequestParam(value = "dateTo", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate dateTo
    );


    String PATH_GET_INVOICES_BY_CLIENT_ID = "/invoices/client/{clientId}";
    /**
     * GET /invoices/client/{clientId} : Obtener todas las facturas de un cliente
     *
     * @param clientId  (required)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param sort Ordenación. Formato: campo,dirección (ej: date,asc). Campos válidos: date, total, status, createdAt. (optional, default to createdAt,desc)
     * @param status Filtrar por estado de la factura. (optional)
     * @param dateFrom Filtrar facturas con fecha mayor o igual a esta (formato: YYYY-MM-DD). (optional)
     * @param dateTo Filtrar facturas con fecha menor o igual a esta (formato: YYYY-MM-DD). (optional)
     * @return Página de facturas del cliente (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Cliente no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "getInvoicesByClientId",
        summary = "Obtener todas las facturas de un cliente",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Página de facturas del cliente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoicePageDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = InvoicesApi.PATH_GET_INVOICES_BY_CLIENT_ID,
        produces = { "application/json" }
    )
    ResponseEntity<InvoicePageDTO> getInvoicesByClientId(
        @Parameter(name = "clientId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Long clientId,
        @Min(value = 0) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(value = 1) @Max(value = 20) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size,
        @Parameter(name = "sort", description = "Ordenación. Formato: campo,dirección (ej: date,asc). Campos válidos: date, total, status, createdAt.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false, defaultValue = "createdAt,desc") String sort,
        @Parameter(name = "status", description = "Filtrar por estado de la factura.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) @Nullable String status,
        @Parameter(name = "dateFrom", description = "Filtrar facturas con fecha mayor o igual a esta (formato: YYYY-MM-DD).", in = ParameterIn.QUERY) @Valid @RequestParam(value = "dateFrom", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate dateFrom,
        @Parameter(name = "dateTo", description = "Filtrar facturas con fecha menor o igual a esta (formato: YYYY-MM-DD).", in = ParameterIn.QUERY) @Valid @RequestParam(value = "dateTo", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate dateTo
    );


    String PATH_PATCH_INVOICE = "/invoices/{invoiceId}";
    /**
     * PATCH /invoices/{invoiceId} : Actualizar parcialmente una factura (JSON Merge Patch)
     * Actualiza solo los campos incluidos en el body. Solo válido para facturas en estado DRAFT (RFC 7396).
     *
     * @param invoiceId  (required)
     * @param patchInvoiceDTO  (required)
     * @return Factura actualizada parcialmente (status code 200)
     *         or Datos inválidos o factura no está en estado DRAFT (status code 400)
     *         or Factura no encontrada (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "patchInvoice",
        summary = "Actualizar parcialmente una factura (JSON Merge Patch)",
        description = "Actualiza solo los campos incluidos en el body. Solo válido para facturas en estado DRAFT (RFC 7396).",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Factura actualizada parcialmente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Datos inválidos o factura no está en estado DRAFT", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = InvoicesApi.PATH_PATCH_INVOICE,
        produces = { "application/json" },
        consumes = { "application/merge-patch+json" }
    )
    ResponseEntity<InvoiceDTO> patchInvoice(
        @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId,
        @Parameter(name = "PatchInvoiceDTO", description = "", required = true) @Valid @RequestBody PatchInvoiceDTO patchInvoiceDTO
    );


    String PATH_PAY_INVOICE = "/invoices/{invoiceId}/pay";
    /**
     * PUT /invoices/{invoiceId}/pay : Marcar factura como pagada
     * Cambia el estado de la factura a PAID.
     *
     * @param invoiceId  (required)
     * @return Factura actualizada a pagada (status code 200)
     *         or Factura no se puede pagar (status code 400)
     *         or Factura no encontrada (status code 404)
     *         or Acceso denegado (status code 403)
     *         or Error interno (status code 500)
     */
    @Operation(
        operationId = "payInvoice",
        summary = "Marcar factura como pagada",
        description = "Cambia el estado de la factura a PAID.",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Factura actualizada a pagada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Factura no se puede pagar", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso denegado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = InvoicesApi.PATH_PAY_INVOICE,
        produces = { "application/json" }
    )
    ResponseEntity<InvoiceDTO> payInvoice(
        @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId
    );


    String PATH_UPDATE_INVOICE = "/invoices/{invoiceId}";
    /**
     * PUT /invoices/{invoiceId} : Actualizar factura existente
     *
     * @param invoiceId  (required)
     * @param newInvoiceDTO  (required)
     * @return Factura actualizada correctamente (status code 200)
     *         or Petición mal formada (status code 400)
     *         or Factura no encontrada (status code 404)
     *         or Acceso prohibido. El usuario no tiene permisos suficientes. (status code 403)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "updateInvoice",
        summary = "Actualizar factura existente",
        tags = { "invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Factura actualizada correctamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "Petición mal formada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Factura no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Acceso prohibido. El usuario no tiene permisos suficientes.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = InvoicesApi.PATH_UPDATE_INVOICE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<InvoiceDTO> updateInvoice(
        @Parameter(name = "invoiceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("invoiceId") Long invoiceId,
        @Parameter(name = "NewInvoiceDTO", description = "", required = true) @Valid @RequestBody NewInvoiceDTO newInvoiceDTO
    );

}
