# -------- STAGE 1: Build --------
FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /app

# 1️ Copiar solo archivos necesarios para dependencias
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn
COPY contract contract


RUN chmod +x mvnw

# 2️ Descargar dependencias (se cachea)
RUN ./mvnw dependency:go-offline

# 3️ Ahora copiar el código fuente
COPY src src

# 4️ Compilar
RUN ./mvnw clean package -DskipTests


# -------- STAGE 2: Runtime --------
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "app.jar"]
